package com.vineyard.aivideostudio.media.video

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Rect
import android.media.MediaMetadataRetriever
import com.google.android.gms.tasks.Tasks
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.Face
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import com.google.mlkit.vision.objects.DetectedObject
import com.google.mlkit.vision.objects.ObjectDetection
import com.google.mlkit.vision.objects.defaults.ObjectDetectorOptions
import com.vineyard.aivideostudio.core.model.PipelineStatus
import com.vineyard.aivideostudio.core.model.effects.BlurSpec
import com.vineyard.aivideostudio.core.model.effects.NormalizedBounds
import com.vineyard.aivideostudio.core.model.effects.TrackingIndicatorSpec
import com.vineyard.aivideostudio.processing.logger.LogSeverity
import com.vineyard.aivideostudio.processing.logger.ProcessingLogger
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import kotlin.math.max
import kotlin.math.min

/**
 * On-device calibrator for physical objects and human faces in Script Mode.
 *
 * Takes Gemini Vision's grounded hypothesis from the Live WebSocket stream,
 * samples uncompressed video frames at trigger timestamps, runs on-device
 * ML Kit detection, and magnetically snaps coordinates to physical pixel edges.
 */
class ObjectAnchorCalibrator(
    private val context: Context,
    private val logger: ProcessingLogger
) {

    companion object {
        private const val FACE_SNAP_THRESHOLD = 0.25f // Max distance allowed for face contour magnetic snap
        private const val OBJECT_MAX_DRIFT_THRESHOLD = 0.12f // Strict max drift to prevent jumping onto background furniture
        private const val OBJECT_MIN_IOU_THRESHOLD = 0.15f // Minimum overlap required to accept an ML Kit object snap
    }

    // High accuracy face detector for precise contour bounding
    private val faceDetector by lazy {
        val options = FaceDetectorOptions.Builder()
            .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE)
            .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_NONE)
            .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_NONE)
            .setMinFaceSize(0.05f)
            .build()
        FaceDetection.getClient(options)
    }

    // Object detector with classification enabled for physical items
    private val objectDetector by lazy {
        val options = ObjectDetectorOptions.Builder()
            .setDetectorMode(ObjectDetectorOptions.SINGLE_IMAGE_MODE)
            .enableMultipleObjects()
            .enableClassification()
            .build()
        ObjectDetection.getClient(options)
    }

    /**
     * Calibrate Blur Specs generated by Script Mode.
     * Samples multiple timestamps across the clip so moving faces remain continuously blurred.
     */
    suspend fun calibrateBlurSpecs(
        videoFile: File,
        blurSpecs: List<BlurSpec>
    ): List<BlurSpec> = withContext(Dispatchers.IO) {
        val activeSpecs = blurSpecs.filter { it.targetType.equals("face", ignoreCase = true) || it.targetType.equals("object", ignoreCase = true) }
        if (activeSpecs.isEmpty()) {
            return@withContext blurSpecs
        }

        logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Starting Script-Mode Auto-Fix calibration for ${activeSpecs.size} blur target(s)...", LogSeverity.INFO)

        val retriever = MediaMetadataRetriever()
        try {
            retriever.setDataSource(videoFile.absolutePath)
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Failed to load video dataSource for calibration: ${e.message}", LogSeverity.ERROR)
            return@withContext blurSpecs
        }

        try {
            blurSpecs.map { spec ->
                val target = spec.targetType?.lowercase()
                if (target == "face" || target == "object") {
                    calibrateSingleBlur(retriever, spec)
                } else {
                    spec
                }
            }
        } finally {
            try {
                retriever.release()
            } catch (_: Exception) {}
        }
    }

    /**
     * Calibrate Tracking Indicators generated by Script Mode.
     * Supports both static bounds and keyframe-interpolated trajectories.
     */
    suspend fun calibrateTrackingIndicators(
        videoFile: File,
        indicators: List<TrackingIndicatorSpec>
    ): List<TrackingIndicatorSpec> = withContext(Dispatchers.IO) {
        val activeIndicators = indicators.filter {
            it.targetType.equals("face", ignoreCase = true) || it.targetType.equals("object", ignoreCase = true)
        }
        if (activeIndicators.isEmpty()) {
            return@withContext indicators
        }

        logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Starting Script-Mode Auto-Fix calibration for ${activeIndicators.size} tracking indicator(s)...", LogSeverity.INFO)

        val retriever = MediaMetadataRetriever()
        try {
            retriever.setDataSource(videoFile.absolutePath)
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Failed to load video dataSource for tracking calibration: ${e.message}", LogSeverity.ERROR)
            return@withContext indicators
        }

        try {
            indicators.map { indicator ->
                val target = indicator.targetType?.lowercase()
                if (target == "face" || target == "object") {
                    calibrateSingleIndicator(retriever, indicator)
                } else {
                    indicator
                }
            }
        } finally {
            try {
                retriever.release()
            } catch (_: Exception) {}
        }
    }

    // ---------------------------------------------------------------------------------------------
    // Internal Calibration Routines
    // ---------------------------------------------------------------------------------------------

    private fun calibrateSingleBlur(
        retriever: MediaMetadataRetriever,
        spec: BlurSpec
    ): BlurSpec {
        val durationMs = (spec.endTimeMs - spec.startTimeMs).coerceAtLeast(1000L)
        val isFaceTarget = spec.targetType.equals("face", ignoreCase = true)

        // For moving faces, sample across start, midpoint, and later intervals to construct a movement envelope
        val sampleTimestamps = if (isFaceTarget && durationMs > 5000L) {
            listOf(
                spec.startTimeMs,
                spec.startTimeMs + (durationMs / 4L),
                spec.startTimeMs + (durationMs / 2L),
                spec.startTimeMs + (3L * durationMs / 4L),
                spec.endTimeMs.coerceAtMost(spec.startTimeMs + 49000L)
            )
        } else {
            listOf(spec.startTimeMs)
        }

        val detectedBoxes = mutableListOf<NormalizedBounds>()

        for (timeMs in sampleTimestamps) {
            val frameBitmap = extractFrame(retriever, timeMs * 1000L) ?: continue
            try {
                val detected = when (spec.targetType?.lowercase()) {
                    "face" -> detectClosestFace(frameBitmap, spec.bounds)
                    "object" -> detectClosestObject(frameBitmap, spec.bounds, spec.objectClass)
                    else -> null
                }
                if (detected != null) {
                    detectedBoxes.add(detected)
                }
            } finally {
                frameBitmap.recycle()
            }
        }

        return if (detectedBoxes.isNotEmpty()) {
            var minLeft = detectedBoxes.minOf { it.left }
            var minTop = detectedBoxes.minOf { it.top }
            var maxRight = detectedBoxes.maxOf { it.right }
            var maxBottom = detectedBoxes.maxOf { it.bottom }

            val padX = (maxRight - minLeft) * 0.10f
            val padY = (maxBottom - minTop) * 0.10f
            minLeft = (minLeft - padX).coerceIn(0.0f, 1.0f)
            minTop = (minTop - padY).coerceIn(0.0f, 1.0f)
            maxRight = (maxRight + padX).coerceIn(0.0f, 1.0f)
            maxBottom = (maxBottom + padY).coerceIn(0.0f, 1.0f)

            val dynamicEnvelope = NormalizedBounds(minLeft, minTop, maxRight, maxBottom)

            logger.log(
                "CALIBRATION",
                PipelineStatus.EXPORTING,
                "🎯 [SNAP-AUTOFIX] Blur target '${spec.targetType}' dynamically tracked across ${detectedBoxes.size} sample(s): " +
                        "L:${"%.3f".format(dynamicEnvelope.left)}, T:${"%.3f".format(dynamicEnvelope.top)}, R:${"%.3f".format(dynamicEnvelope.right)}, B:${"%.3f".format(dynamicEnvelope.bottom)}",
                LogSeverity.SUCCESS
            )
            spec.copy(bounds = dynamicEnvelope)
        } else {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "⚠️ [SNAP-FALLBACK] Preserving script bounds for blur at ${spec.startTimeMs}ms.", LogSeverity.INFO)
            spec
        }
    }

    private fun calibrateSingleIndicator(
        retriever: MediaMetadataRetriever,
        indicator: TrackingIndicatorSpec
    ): TrackingIndicatorSpec {
        val isKeyframes = indicator.trackingMode.equals("keyframes", ignoreCase = true) && !indicator.keyframes.isNullOrEmpty()

        return if (isKeyframes) {
            val calibratedKeyframes = indicator.keyframes!!.map { kf ->
                val frameBitmap = extractFrame(retriever, kf.timeMs * 1000L) ?: return@map kf
                try {
                    val initialBounds = NormalizedBounds(
                        left = (kf.x - (kf.width / 2f)).coerceIn(0.0f, 1.0f),
                        top = (kf.y - (kf.height / 2f)).coerceIn(0.0f, 1.0f),
                        right = (kf.x + (kf.width / 2f)).coerceIn(0.0f, 1.0f),
                        bottom = (kf.y + (kf.height / 2f)).coerceIn(0.0f, 1.0f)
                    )

                    val detectedBounds = when (indicator.targetType?.lowercase()) {
                        "face" -> detectClosestFace(frameBitmap, initialBounds)
                        "object" -> detectClosestObject(frameBitmap, initialBounds, indicator.objectClass)
                        else -> null
                    }

                    if (detectedBounds != null) {
                        val newWidth = detectedBounds.right - detectedBounds.left
                        val newHeight = detectedBounds.bottom - detectedBounds.top
                        val newCenterX = detectedBounds.left + (newWidth / 2f)
                        val newCenterY = detectedBounds.top + (newHeight / 2f)

                        kf.copy(
                            x = newCenterX,
                            y = newCenterY,
                            width = newWidth,
                            height = newHeight
                        )
                    } else {
                        kf
                    }
                } finally {
                    frameBitmap.recycle()
                }
            }

            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "🎯 [SNAP-AUTOFIX] Calibrated ${calibratedKeyframes.size} keyframes for target '${indicator.id}'", LogSeverity.SUCCESS)
            indicator.copy(keyframes = calibratedKeyframes)
        } else {
            val initialBounds = indicator.staticBounds ?: return indicator
            val frameBitmap = extractFrame(retriever, indicator.startTimeMs * 1000L) ?: return indicator

            try {
                val detectedBounds = when (indicator.targetType?.lowercase()) {
                    "face" -> detectClosestFace(frameBitmap, initialBounds)
                    "object" -> detectClosestObject(frameBitmap, initialBounds, indicator.objectClass)
                    else -> null
                }

                if (detectedBounds != null) {
                    logger.log(
                        "CALIBRATION",
                        PipelineStatus.EXPORTING,
                        "🎯 [SNAP-AUTOFIX] Indicator '${indicator.id}' (${indicator.label}) tightened to physical edges at ${indicator.startTimeMs}ms",
                        LogSeverity.SUCCESS
                    )
                    indicator.copy(staticBounds = detectedBounds)
                } else {
                    logger.log(
                        "CALIBRATION",
                        PipelineStatus.EXPORTING,
                        "🔒 [ANCHOR-LOCK] Indicator '${indicator.id}' (${indicator.label}) locked firmly to Gemini Vision anchor (furniture distraction rejected).",
                        LogSeverity.INFO
                    )
                    indicator
                }
            } finally {
                frameBitmap.recycle()
            }
        }
    }

    // ---------------------------------------------------------------------------------------------
    // ML Kit Detection & Proximity / IoU Gating
    // ---------------------------------------------------------------------------------------------

    private fun detectClosestFace(bitmap: Bitmap, scriptBounds: NormalizedBounds): NormalizedBounds? {
        val image = InputImage.fromBitmap(bitmap, 0)
        return try {
            val task = faceDetector.process(image)
            val faces: List<Face> = Tasks.await(task)

            if (faces.isEmpty()) return null

            val width = bitmap.width.toFloat()
            val height = bitmap.height.toFloat()

            var bestFaceBounds: NormalizedBounds? = null
            var minDistance = Float.MAX_VALUE

            for (face in faces) {
                val normBounds = face.boundingBox.toNormalizedBounds(width, height)
                val dist = calculateDistance(normBounds, scriptBounds)
                if (dist < minDistance && dist <= FACE_SNAP_THRESHOLD) {
                    minDistance = dist
                    bestFaceBounds = normBounds
                }
            }
            bestFaceBounds
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "ML Kit Face detection error: ${e.message}", LogSeverity.ERROR)
            null
        }
    }

    /**
     * Inspects on-device objects using strict IoU overlap gating against Gemini Vision's anchor.
     * Prevents ML Kit from snapping onto nearby furniture, shelves, or walls.
     */
    private fun detectClosestObject(
        bitmap: Bitmap,
        anchorBounds: NormalizedBounds,
        expectedClass: String?
    ): NormalizedBounds? {
        val image = InputImage.fromBitmap(bitmap, 0)
        return try {
            val task = objectDetector.process(image)
            val detectedObjects: List<DetectedObject> = Tasks.await(task)

            if (detectedObjects.isEmpty()) return null

            val width = bitmap.width.toFloat()
            val height = bitmap.height.toFloat()

            var bestObjectBounds: NormalizedBounds? = null
            var bestIoU = 0.0f
            var minDistance = Float.MAX_VALUE

            for (obj in detectedObjects) {
                val normBounds = obj.boundingBox.toNormalizedBounds(width, height)
                val dist = calculateDistance(normBounds, anchorBounds)
                val iou = calculateIoU(normBounds, anchorBounds)

                // Reject objects that do not overlap the anchor or drift too far into surrounding furniture
                if (dist > OBJECT_MAX_DRIFT_THRESHOLD && iou < OBJECT_MIN_IOU_THRESHOLD) {
                    continue
                }

                var weight = 1.0f
                if (!expectedClass.isNullOrBlank()) {
                    val hasLabelMatch = obj.labels.any { it.text.contains(expectedClass, ignoreCase = true) }
                    if (hasLabelMatch) weight = 0.6f // Prioritize category match
                }

                val score = (dist * weight) - (iou * 0.5f)
                if (score < minDistance && (iou >= OBJECT_MIN_IOU_THRESHOLD || dist <= OBJECT_MAX_DRIFT_THRESHOLD)) {
                    minDistance = score
                    bestIoU = iou
                    bestObjectBounds = normBounds
                }
            }

            bestObjectBounds
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "ML Kit Object detection error: ${e.message}", LogSeverity.ERROR)
            null
        }
    }

    // ---------------------------------------------------------------------------------------------
    // Geometry & Math Utilities
    // ---------------------------------------------------------------------------------------------

    private fun extractFrame(retriever: MediaMetadataRetriever, timeUs: Long): Bitmap? {
        return try {
            retriever.getFrameAtTime(timeUs, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Unable to extract frame at ${timeUs / 1000}ms: ${e.message}", LogSeverity.WARNING)
            null
        }
    }

    private fun Rect.toNormalizedBounds(imageWidth: Float, imageHeight: Float): NormalizedBounds {
        return NormalizedBounds(
            left = (this.left / imageWidth).coerceIn(0.0f, 1.0f),
            top = (this.top / imageHeight).coerceIn(0.0f, 1.0f),
            right = (this.right / imageWidth).coerceIn(0.0f, 1.0f),
            bottom = (this.bottom / imageHeight).coerceIn(0.0f, 1.0f)
        )
    }

    private fun calculateDistance(a: NormalizedBounds, b: NormalizedBounds): Float {
        val centerAx = (a.left + a.right) / 2f
        val centerAy = (a.top + a.bottom) / 2f
        val centerBx = (b.left + b.right) / 2f
        val centerBy = (b.top + b.bottom) / 2f
        val dx = centerAx - centerBx
        val dy = centerAy - centerBy
        return kotlin.math.sqrt((dx * dx + dy * dy).toDouble()).toFloat()
    }

    /**
     * Calculates Intersection-over-Union (IoU) between two bounding boxes.
     */
    private fun calculateIoU(a: NormalizedBounds, b: NormalizedBounds): Float {
        val interLeft = max(a.left, b.left)
        val interTop = max(a.top, b.top)
        val interRight = min(a.right, b.right)
        val interBottom = min(a.bottom, b.bottom)

        val interWidth = max(0.0f, interRight - interLeft)
        val interHeight = max(0.0f, interBottom - interTop)
        val interArea = interWidth * interHeight

        val areaA = (a.right - a.left) * (a.bottom - a.top)
        val areaB = (b.right - b.left) * (b.bottom - b.top)
        val unionArea = areaA + areaB - interArea

        return if (unionArea > 0.0f) interArea / unionArea else 0.0f
    }
}