package com.vineyard.aivideostudio.media.video

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Rect
import android.media.MediaMetadataRetriever
import com.google.android.gms.tasks.Tasks
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.Face
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import com.google.mlkit.vision.objects.DetectedObject
import com.google.mlkit.vision.objects.ObjectDetection
import com.google.mlkit.vision.objects.defaults.ObjectDetectorOptions
import com.vineyard.aivideostudio.core.model.PipelineStatus
import com.vineyard.aivideostudio.core.model.effects.BlurSpec
import com.vineyard.aivideostudio.core.model.effects.NormalizedBounds
import com.vineyard.aivideostudio.core.model.effects.TrackingIndicatorSpec
import com.vineyard.aivideostudio.processing.logger.LogSeverity
import com.vineyard.aivideostudio.processing.logger.ProcessingLogger
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import kotlin.math.max
import kotlin.math.min

/**
 * On-device calibrator for physical objects and human faces in Script Mode.
 *
 * Implements dynamic timeline column tracking for moving heads and
 * strict stationary margin constraints for physical objects.
 */
class ObjectAnchorCalibrator(
    private val context: Context,
    private val logger: ProcessingLogger
) {

    companion object {
        private const val FACE_SNAP_THRESHOLD = 0.32f // Expanded threshold to capture steep head tilts & yaw
        private const val OBJECT_MAX_DRIFT_THRESHOLD = 0.18f // Max allowed drift for physical objects
        private const val OBJECT_MIN_IOU_THRESHOLD = 0.08f // Minimum overlap required to accept an ML Kit object snap
        private const val DYNAMIC_SLICE_STEP_MS = 1000L // 1.0-second high-frequency tracking slices
    }

    // High accuracy face detector for precise contour bounding
    private val faceDetector by lazy {
        val options = FaceDetectorOptions.Builder()
            .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE)
            .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_NONE)
            .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_NONE)
            .setMinFaceSize(0.05f)
            .build()
        FaceDetection.getClient(options)
    }

    // Object detector with classification enabled for physical items
    private val objectDetector by lazy {
        val options = ObjectDetectorOptions.Builder()
            .setDetectorMode(ObjectDetectorOptions.SINGLE_IMAGE_MODE)
            .enableMultipleObjects()
            .enableClassification()
            .build()
        ObjectDetection.getClient(options)
    }

    /**
     * Calibrates Blur Specs and generates dynamic timeline slices so moving faces remain continuously blurred.
     */
    suspend fun calibrateBlurSpecs(
        videoFile: File,
        blurSpecs: List<BlurSpec>
    ): List<BlurSpec> = withContext(Dispatchers.IO) {
        val activeSpecs = blurSpecs.filter { it.targetType.equals("face", ignoreCase = true) || it.targetType.equals("object", ignoreCase = true) }
        if (activeSpecs.isEmpty()) {
            return@withContext blurSpecs
        }

        logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Starting Column-Tracked Auto-Fix calibration for ${activeSpecs.size} blur target(s)...", LogSeverity.INFO)

        val retriever = MediaMetadataRetriever()
        try {
            retriever.setDataSource(videoFile.absolutePath)
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Failed to load video dataSource for calibration: ${e.message}", LogSeverity.ERROR)
            return@withContext blurSpecs
        }

        try {
            val resultSpecs = mutableListOf<BlurSpec>()
            for (spec in blurSpecs) {
                val target = spec.targetType?.lowercase()
                if (target == "face" || target == "object") {
                    resultSpecs.addAll(calibrateAndSliceBlur(retriever, spec))
                } else {
                    resultSpecs.add(spec)
                }
            }
            resultSpecs
        } finally {
            try {
                retriever.release()
            } catch (_: Exception) {}
        }
    }

    /**
     * Calibrate Tracking Indicators generated by Script Mode.
     * Supports both static bounds and keyframe-interpolated trajectories.
     */
    suspend fun calibrateTrackingIndicators(
        videoFile: File,
        indicators: List<TrackingIndicatorSpec>
    ): List<TrackingIndicatorSpec> = withContext(Dispatchers.IO) {
        val activeIndicators = indicators.filter {
            it.targetType.equals("face", ignoreCase = true) || it.targetType.equals("object", ignoreCase = true)
        }
        if (activeIndicators.isEmpty()) {
            return@withContext indicators
        }

        logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Starting Script-Mode Auto-Fix calibration for ${activeIndicators.size} tracking indicator(s)...", LogSeverity.INFO)

        val retriever = MediaMetadataRetriever()
        try {
            retriever.setDataSource(videoFile.absolutePath)
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Failed to load video dataSource for tracking calibration: ${e.message}", LogSeverity.ERROR)
            return@withContext indicators
        }

        try {
            indicators.map { indicator ->
                val target = indicator.targetType?.lowercase()
                if (target == "face" || target == "object") {
                    calibrateSingleIndicator(retriever, indicator)
                } else {
                    indicator
                }
            }
        } finally {
            try {
                retriever.release()
            } catch (_: Exception) {}
        }
    }

    // ---------------------------------------------------------------------------------------------
    // Internal Calibration Routines
    // ---------------------------------------------------------------------------------------------

    /**
     * Slices a long blur specification into continuous dynamic timeline intervals following the subject's motion column.
     */
    private fun calibrateAndSliceBlur(
        retriever: MediaMetadataRetriever,
        spec: BlurSpec
    ): List<BlurSpec> {
        val durationMs = spec.endTimeMs - spec.startTimeMs
        val isFaceTarget = spec.targetType.equals("face", ignoreCase = true)

        if (!isFaceTarget || durationMs <= 1500L) {
            val single = calibrateSingleBlurFrame(retriever, spec, spec.startTimeMs)
            return listOf(single)
        }

        val sliceStepMs = DYNAMIC_SLICE_STEP_MS
        val slices = mutableListOf<BlurSpec>()
        var cursorStartMs = spec.startTimeMs

        // Establish the target's distinct Motion Column (X-margin) from initial detection
        val initialFrame = extractFrame(retriever, spec.startTimeMs * 1000L)
        val initialFace = if (initialFrame != null) {
            try { detectClosestFace(initialFrame, spec.bounds) } finally { initialFrame.recycle() }
        } else null

        var lastKnownBounds = initialFace ?: spec.bounds
        val motionColumnMinX = (lastKnownBounds.left - 0.12f).coerceIn(0.0f, 1.0f)
        val motionColumnMaxX = (lastKnownBounds.right + 0.12f).coerceIn(0.0f, 1.0f)

        while (cursorStartMs < spec.endTimeMs) {
            val cursorEndMs = minOf(cursorStartMs + sliceStepMs, spec.endTimeMs)
            val sampleTimeMs = cursorStartMs + ((cursorEndMs - cursorStartMs) / 2L)
            val frameBitmap = extractFrame(retriever, sampleTimeMs * 1000L)

            val detectedFace = if (frameBitmap != null) {
                try {
                    detectClosestFaceInColumn(frameBitmap, lastKnownBounds, motionColumnMinX, motionColumnMaxX)
                } finally {
                    frameBitmap.recycle()
                }
            } else null

            val sliceBounds = if (detectedFace != null) {
                lastKnownBounds = detectedFace
                detectedFace
            } else {
                lastKnownBounds
            }

            slices.add(
                spec.copy(
                    startTimeMs = cursorStartMs,
                    endTimeMs = cursorEndMs,
                    bounds = sliceBounds
                )
            )

            cursorStartMs = cursorEndMs
        }

        logger.log(
            "CALIBRATION",
            PipelineStatus.EXPORTING,
            "🎯 [DYNAMIC-COLUMN-BLUR] Sliced target '${spec.targetType}' into ${slices.size} dynamic timeline interval(s) across Column [X: ${"%.2f".format(motionColumnMinX)}..${"%.2f".format(motionColumnMaxX)}]",
            LogSeverity.SUCCESS
        )

        return slices
    }

    private fun calibrateSingleBlurFrame(
        retriever: MediaMetadataRetriever,
        spec: BlurSpec,
        timestampMs: Long
    ): BlurSpec {
        val frameBitmap = extractFrame(retriever, timestampMs * 1000L) ?: return spec
        return try {
            val detected = when (spec.targetType?.lowercase()) {
                "face" -> detectClosestFace(frameBitmap, spec.bounds)
                "object" -> detectClosestObject(frameBitmap, spec.bounds, spec.objectClass)
                else -> null
            }
            if (detected != null) {
                spec.copy(bounds = detected)
            } else {
                spec
            }
        } finally {
            frameBitmap.recycle()
        }
    }

    private fun calibrateSingleIndicator(
        retriever: MediaMetadataRetriever,
        indicator: TrackingIndicatorSpec
    ): TrackingIndicatorSpec {
        val isKeyframes = indicator.trackingMode.equals("keyframes", ignoreCase = true) && !indicator.keyframes.isNullOrEmpty()

        return if (isKeyframes) {
            val calibratedKeyframes = indicator.keyframes!!.map { kf ->
                val frameBitmap = extractFrame(retriever, kf.timeMs * 1000L) ?: return@map kf
                try {
                    val initialBounds = NormalizedBounds(
                        left = (kf.x - (kf.width / 2f)).coerceIn(0.0f, 1.0f),
                        top = (kf.y - (kf.height / 2f)).coerceIn(0.0f, 1.0f),
                        right = (kf.x + (kf.width / 2f)).coerceIn(0.0f, 1.0f),
                        bottom = (kf.y + (kf.height / 2f)).coerceIn(0.0f, 1.0f)
                    )

                    val detectedBounds = when (indicator.targetType?.lowercase()) {
                        "face" -> detectClosestFace(frameBitmap, initialBounds)
                        "object" -> detectClosestObject(frameBitmap, initialBounds, indicator.objectClass)
                        else -> null
                    }

                    if (detectedBounds != null) {
                        val newWidth = detectedBounds.right - detectedBounds.left
                        val newHeight = detectedBounds.bottom - detectedBounds.top
                        val newCenterX = detectedBounds.left + (newWidth / 2f)
                        val newCenterY = detectedBounds.top + (newHeight / 2f)

                        kf.copy(
                            x = newCenterX,
                            y = newCenterY,
                            width = newWidth,
                            height = newHeight
                        )
                    } else {
                        kf
                    }
                } finally {
                    frameBitmap.recycle()
                }
            }

            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "🎯 [SNAP-AUTOFIX] Calibrated ${calibratedKeyframes.size} keyframes for target '${indicator.id}'", LogSeverity.SUCCESS)
            indicator.copy(keyframes = calibratedKeyframes)
        } else {
            val initialBounds = indicator.staticBounds ?: return indicator
            val frameBitmap = extractFrame(retriever, indicator.startTimeMs * 1000L) ?: return indicator

            try {
                val detectedBounds = when (indicator.targetType?.lowercase()) {
                    "face" -> detectClosestFace(frameBitmap, initialBounds)
                    "object" -> detectClosestObject(frameBitmap, initialBounds, indicator.objectClass)
                    else -> null
                }

                if (detectedBounds != null) {
                    logger.log(
                        "CALIBRATION",
                        PipelineStatus.EXPORTING,
                        "🎯 [SNAP-AUTOFIX] Indicator '${indicator.id}' (${indicator.label}) tightened to physical edges at ${indicator.startTimeMs}ms",
                        LogSeverity.SUCCESS
                    )
                    indicator.copy(staticBounds = detectedBounds)
                } else {
                    logger.log(
                        "CALIBRATION",
                        PipelineStatus.EXPORTING,
                        "🔒 [ANCHOR-LOCK] Indicator '${indicator.id}' (${indicator.label}) locked firmly to Gemini Vision anchor (furniture distraction rejected).",
                        LogSeverity.INFO
                    )
                    indicator
                }
            } finally {
                frameBitmap.recycle()
            }
        }
    }

    // ---------------------------------------------------------------------------------------------
    // ML Kit Detection & Proximity / IoU Gating
    // ---------------------------------------------------------------------------------------------

    private fun detectClosestFace(bitmap: Bitmap, scriptBounds: NormalizedBounds): NormalizedBounds? {
        val image = InputImage.fromBitmap(bitmap, 0)
        return try {
            val task = faceDetector.process(image)
            val faces: List<Face> = Tasks.await(task)

            if (faces.isEmpty()) return null

            val width = bitmap.width.toFloat()
            val height = bitmap.height.toFloat()

            var bestFaceBounds: NormalizedBounds? = null
            var minDistance = Float.MAX_VALUE

            for (face in faces) {
                val normBounds = face.boundingBox.toNormalizedBounds(width, height)
                val dist = calculateDistance(normBounds, scriptBounds)
                if (dist < minDistance && dist <= FACE_SNAP_THRESHOLD) {
                    minDistance = dist
                    bestFaceBounds = normBounds
                }
            }
            bestFaceBounds
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "ML Kit Face detection error: ${e.message}", LogSeverity.ERROR)
            null
        }
    }

    private fun detectClosestFaceInColumn(
        bitmap: Bitmap,
        lastBounds: NormalizedBounds,
        minX: Float,
        maxX: Float
    ): NormalizedBounds? {
        val image = InputImage.fromBitmap(bitmap, 0)
        return try {
            val task = faceDetector.process(image)
            val faces: List<Face> = Tasks.await(task)
            if (faces.isEmpty()) return null

            val width = bitmap.width.toFloat()
            val height = bitmap.height.toFloat()

            var bestFace: NormalizedBounds? = null
            var minDistance = Float.MAX_VALUE

            for (face in faces) {
                val normBounds = face.boundingBox.toNormalizedBounds(width, height)
                // Ensure face center is within the subject's assigned motion column
                if (normBounds.centerX < minX || normBounds.centerX > maxX) {
                    continue
                }

                val dist = calculateDistance(normBounds, lastBounds)
                if (dist < minDistance && dist <= FACE_SNAP_THRESHOLD) {
                    minDistance = dist
                    bestFace = normBounds
                }
            }
            bestFace
        } catch (_: Exception) {
            null
        }
    }

    /**
     * Inspects on-device objects using adaptive IoU overlap gating against Gemini Vision's anchor.
     * Prevents ML Kit from snapping onto background furniture while supporting generic objects.
     */
    private fun detectClosestObject(
        bitmap: Bitmap,
        anchorBounds: NormalizedBounds,
        expectedClass: String?
    ): NormalizedBounds? {
        val image = InputImage.fromBitmap(bitmap, 0)
        return try {
            val task = objectDetector.process(image)
            val detectedObjects: List<DetectedObject> = Tasks.await(task)

            if (detectedObjects.isEmpty()) return null

            val width = bitmap.width.toFloat()
            val height = bitmap.height.toFloat()

            var bestObjectBounds: NormalizedBounds? = null
            var bestIoU = 0.0f
            var minDistance = Float.MAX_VALUE

            for (obj in detectedObjects) {
                val normBounds = obj.boundingBox.toNormalizedBounds(width, height)
                val dist = calculateDistance(normBounds, anchorBounds)
                val iou = calculateIoU(normBounds, anchorBounds)

                // Reject objects that do not overlap the anchor or drift too far into surrounding furniture
                if (dist > OBJECT_MAX_DRIFT_THRESHOLD && iou < OBJECT_MIN_IOU_THRESHOLD) {
                    continue
                }

                var weight = 1.0f
                if (!expectedClass.isNullOrBlank()) {
                    val hasLabelMatch = obj.labels.any { it.text.contains(expectedClass, ignoreCase = true) }
                    if (hasLabelMatch) weight = 0.6f // Prioritize category match
                }

                val score = (dist * weight) - (iou * 0.5f)
                if (score < minDistance && (iou >= OBJECT_MIN_IOU_THRESHOLD || dist <= OBJECT_MAX_DRIFT_THRESHOLD)) {
                    minDistance = score
                    bestIoU = iou
                    bestObjectBounds = normBounds
                }
            }

            bestObjectBounds
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "ML Kit Object detection error: ${e.message}", LogSeverity.ERROR)
            null
        }
    }

    // ---------------------------------------------------------------------------------------------
    // Geometry & Math Utilities
    // ---------------------------------------------------------------------------------------------

    private fun extractFrame(retriever: MediaMetadataRetriever, timeUs: Long): Bitmap? {
        return try {
            retriever.getFrameAtTime(timeUs, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)
        } catch (e: Exception) {
            logger.log("CALIBRATION", PipelineStatus.EXPORTING, "Unable to extract frame at ${timeUs / 1000}ms: ${e.message}", LogSeverity.WARNING)
            null
        }
    }

    private fun Rect.toNormalizedBounds(imageWidth: Float, imageHeight: Float): NormalizedBounds {
        return NormalizedBounds(
            left = (this.left / imageWidth).coerceIn(0.0f, 1.0f),
            top = (this.top / imageHeight).coerceIn(0.0f, 1.0f),
            right = (this.right / imageWidth).coerceIn(0.0f, 1.0f),
            bottom = (this.bottom / imageHeight).coerceIn(0.0f, 1.0f)
        )
    }

    private fun calculateDistance(a: NormalizedBounds, b: NormalizedBounds): Float {
        val centerAx = (a.left + a.right) / 2f
        val centerAy = (a.top + a.bottom) / 2f
        val centerBx = (b.left + b.right) / 2f
        val centerBy = (b.top + b.bottom) / 2f
        val dx = centerAx - centerBx
        val dy = centerAy - centerBy
        return kotlin.math.sqrt((dx * dx + dy * dy).toDouble()).toFloat()
    }

    /**
     * Calculates Intersection-over-Union (IoU) between two bounding boxes.
     */
    private fun calculateIoU(a: NormalizedBounds, b: NormalizedBounds): Float {
        val interLeft = max(a.left, b.left)
        val interTop = max(a.top, b.top)
        val interRight = min(a.right, b.right)
        val interBottom = min(a.bottom, b.bottom)

        val interWidth = max(0.0f, interRight - interLeft)
        val interHeight = max(0.0f, interBottom - interTop)
        val interArea = interWidth * interHeight

        val areaA = (a.right - a.left) * (a.bottom - a.top)
        val areaB = (b.right - b.left) * (b.bottom - b.top)
        val unionArea = areaA + areaB - interArea

        return if (unionArea > 0.0f) interArea / unionArea else 0.0f
    }
}